// SPDX-License-Identifier: GPL-2.0

//! The data types of sb/errors_format.h, which is generated from this file: see
//! fs/types/lib.rs. Translated from the C by c2rs.

#![allow(non_camel_case_types)]

use crate::cstructs::c;
use zerocopy::byteorder::little_endian as le;
use cstruct_macros::{bitfield, c_bitmask, c_const, c_enum, c_xmacro, CStruct};
use typeinfo_macros::TypeInfo;

c_enum! {
    #[flags]
    pub enum bch_fsck_flags: u32 {
        FSCK_CAN_FIX = 1 << 0,
        FSCK_CAN_IGNORE = 1 << 1,
        FSCK_AUTOFIX = 1 << 2,
        FSCK_ERR_NO_LOG = 1 << 3,
        FSCK_ERR_SILENT = 1 << 4,
    }
}

c_xmacro! {
    BCH_SB_ERRS(x) {
        (clean_but_journal_not_empty, 0, 0),
        (dirty_but_no_journal_entries, 1, 0),
        (dirty_but_no_journal_entries_post_drop_nonflushes, 2, 0),
        (sb_clean_journal_seq_mismatch, 3, FSCK_AUTOFIX),
        (sb_clean_btree_root_mismatch, 4, 0),
        (sb_clean_missing, 5, FSCK_AUTOFIX),
        (jset_unsupported_version, 6, 0),
        (jset_unknown_csum, 7, 0),
        (jset_last_seq_newer_than_seq, 8, 0),
        (jset_past_bucket_end, 9, 0),
        (jset_seq_blacklisted, 10, 0),
        (journal_entries_missing, 11, FSCK_AUTOFIX),
        (journal_entry_replicas_not_marked, 12, FSCK_AUTOFIX),
        (journal_entry_past_jset_end, 13, 0),
        (journal_entry_replicas_data_mismatch, 14, 0),
        (journal_entry_bkey_u64s_0, 15, 0),
        (journal_entry_bkey_past_end, 16, 0),
        (journal_entry_bkey_bad_format, 17, 0),
        (journal_entry_bkey_invalid, 18, 0),
        (journal_entry_btree_root_bad_size, 19, 0),
        (journal_entry_blacklist_bad_size, 20, 0),
        (journal_entry_blacklist_v2_bad_size, 21, 0),
        (journal_entry_blacklist_v2_start_past_end, 22, 0),
        (journal_entry_usage_bad_size, 23, 0),
        (journal_entry_data_usage_bad_size, 24, 0),
        (journal_entry_clock_bad_size, 25, 0),
        (journal_entry_clock_bad_rw, 26, 0),
        (journal_entry_dev_usage_bad_size, 27, 0),
        (journal_entry_dev_usage_bad_dev, 28, 0),
        (journal_entry_dev_usage_bad_pad, 29, 0),
        (journal_entry_rewind_limit_bad_size, 355, 0),
        (journal_entry_rewind_bad_size, 356, 0),
        (btree_node_unreadable, 30, 0),
        (btree_node_fault_injected, 31, 0),
        (btree_node_bad_magic, 32, 0),
        (btree_node_bad_seq, 33, 0),
        (btree_node_unsupported_version, 34, 0),
        (btree_node_bset_older_than_sb_min, 35, 0),
        (btree_node_bset_newer_than_sb, 36, 0),
        (btree_node_data_missing, 37, FSCK_AUTOFIX),
        (btree_node_bset_after_end, 38, 0),
        (btree_node_replicas_sectors_written_mismatch, 39, 0),
        (btree_node_replicas_data_mismatch, 40, 0),
        (bset_unknown_csum, 41, 0),
        (bset_bad_csum, 42, FSCK_AUTOFIX),
        (bset_past_end_of_btree_node, 43, 0),
        (bset_wrong_sector_offset, 44, 0),
        (bset_empty, 45, 0),
        (bset_bad_seq, 46, 0),
        (bset_blacklisted_journal_seq, 47, FSCK_AUTOFIX),
        (first_bset_blacklisted_journal_seq, 48, FSCK_AUTOFIX),
        (btree_node_bad_btree, 49, 0),
        (btree_node_bad_level, 50, 0),
        (btree_node_bad_min_key, 51, 0),
        (btree_node_bad_max_key, 52, 0),
        (btree_node_bad_format, 53, 0),
        (btree_node_bkey_past_bset_end, 54, 0),
        (btree_node_bkey_bad_format, 55, 0),
        (btree_node_bad_bkey, 56, 0),
        (btree_node_bkey_out_of_order, 57, FSCK_AUTOFIX),
        (btree_root_bkey_invalid, 58, FSCK_AUTOFIX),
        (btree_root_read_error, 59, FSCK_AUTOFIX),
        (btree_root_bad_min_key, 60, 0),
        (btree_root_bad_max_key, 61, 0),
        (btree_node_read_error, 62, FSCK_AUTOFIX),
        (btree_node_topology_gap_between_nodes, 328, FSCK_AUTOFIX),
        (btree_node_topology_bad_min_key, 63, FSCK_AUTOFIX),
        (btree_node_topology_bad_max_key, 64, FSCK_AUTOFIX),
        (btree_node_topology_bad_root_min_key, 323, FSCK_AUTOFIX),
        (btree_node_topology_bad_root_max_key, 324, FSCK_AUTOFIX),
        (btree_node_topology_overwritten_by_prev_node, 65, FSCK_AUTOFIX),
        (btree_node_topology_overwritten_by_next_node, 66, FSCK_AUTOFIX),
        (btree_node_topology_interior_node_empty, 67, FSCK_AUTOFIX),
        (fs_usage_hidden_wrong, 68, FSCK_AUTOFIX),
        (fs_usage_btree_wrong, 69, FSCK_AUTOFIX),
        (fs_usage_data_wrong, 70, FSCK_AUTOFIX),
        (fs_usage_cached_wrong, 71, FSCK_AUTOFIX),
        (fs_usage_reserved_wrong, 72, FSCK_AUTOFIX),
        (fs_usage_persistent_reserved_wrong, 73, FSCK_AUTOFIX),
        (fs_usage_nr_inodes_wrong, 74, FSCK_AUTOFIX),
        (fs_usage_replicas_wrong, 75, FSCK_AUTOFIX),
        (dev_usage_buckets_wrong, 76, FSCK_AUTOFIX),
        (dev_usage_sectors_wrong, 77, FSCK_AUTOFIX),
        (dev_usage_fragmented_wrong, 78, FSCK_AUTOFIX),
        (dev_usage_buckets_ec_wrong, 79, FSCK_AUTOFIX),
        (bkey_version_in_future, 80, 0),
        (bkey_u64s_too_small, 81, 0),
        (bkey_invalid_type_for_btree, 82, 0),
        (bkey_extent_size_zero, 83, 0),
        (bkey_extent_size_greater_than_offset, 84, 0),
        (bkey_size_nonzero, 85, 0),
        (bkey_snapshot_nonzero, 86, 0),
        (bkey_snapshot_zero, 87, 0),
        (bkey_at_pos_max, 88, 0),
        (bkey_before_start_of_btree_node, 89, 0),
        (bkey_after_end_of_btree_node, 90, 0),
        (bkey_val_size_nonzero, 91, 0),
        (bkey_val_size_too_small, 92, 0),
        (alloc_v1_val_size_bad, 93, 0),
        (alloc_v2_unpack_error, 94, 0),
        (alloc_v3_unpack_error, 95, 0),
        (alloc_v4_val_size_bad, 96, 0),
        (alloc_v4_backpointers_start_bad, 97, 0),
        (alloc_key_data_type_bad, 98, 0),
        (alloc_key_empty_but_have_data, 99, 0),
        (alloc_key_dirty_sectors_0, 100, 0),
        (alloc_key_data_type_inconsistency, 101, 0),
        (alloc_key_to_missing_dev_bucket, 102, 0),
        (alloc_key_cached_inconsistency, 103, 0),
        (alloc_key_cached_but_read_time_zero, 104, FSCK_AUTOFIX),
        (alloc_key_to_missing_lru_entry, 105, FSCK_AUTOFIX),
        (alloc_key_data_type_wrong, 106, FSCK_AUTOFIX),
        (alloc_key_gen_wrong, 107, FSCK_AUTOFIX),
        (alloc_key_dirty_sectors_wrong, 108, FSCK_AUTOFIX),
        (alloc_key_cached_sectors_wrong, 109, FSCK_AUTOFIX),
        (alloc_key_stripe_wrong, 110, FSCK_AUTOFIX),
        (alloc_key_stripe_redundancy_wrong, 111, FSCK_AUTOFIX),
        (alloc_key_journal_seq_in_future, 298, FSCK_AUTOFIX),
        (alloc_key_stripe_refcount_wrong, 345, FSCK_AUTOFIX),
        (alloc_key_bucket_nonempty_to_empty_not_open, 353, 0),
        (alloc_key_data_type_free_dirty_bookkeeping, 359, FSCK_AUTOFIX),
        (bucket_sector_count_overflow, 112, 0),
        (bucket_metadata_type_mismatch, 113, 0),
        (need_discard_key_wrong, 114, FSCK_AUTOFIX),
        (freespace_key_wrong, 115, FSCK_AUTOFIX),
        (freespace_hole_missing, 116, FSCK_AUTOFIX),
        (bucket_gens_val_size_bad, 117, 0),
        (bucket_gens_key_wrong, 118, FSCK_AUTOFIX),
        (bucket_gens_hole_wrong, 119, FSCK_AUTOFIX),
        (bucket_gens_to_invalid_dev, 120, FSCK_AUTOFIX),
        (bucket_gens_to_invalid_buckets, 121, FSCK_AUTOFIX),
        (bucket_gens_nonzero_for_invalid_buckets, 122, FSCK_AUTOFIX),
        (need_discard_freespace_key_to_invalid_dev_bucket, 123, FSCK_AUTOFIX),
        (need_discard_freespace_key_bad, 124, FSCK_AUTOFIX),
        (discarding_bucket_not_in_need_discard_btree, 291, 0),
        (backpointer_bucket_offset_wrong, 125, 0),
        (backpointer_level_bad, 294, 0),
        (backpointer_dev_bad, 297, 0),
        (backpointer_to_missing_device, 126, FSCK_AUTOFIX),
        (backpointer_to_missing_alloc, 127, FSCK_AUTOFIX),
        (backpointer_to_missing_ptr, 128, FSCK_AUTOFIX),
        (lru_entry_at_time_0, 129, FSCK_AUTOFIX),
        (lru_entry_to_invalid_bucket, 130, FSCK_AUTOFIX),
        (lru_entry_bad, 131, FSCK_AUTOFIX),
        (btree_ptr_val_too_big, 132, 0),
        (btree_ptr_v2_val_too_big, 133, 0),
        (btree_ptr_has_non_ptr, 134, 0),
        (extent_ptrs_invalid_entry, 135, 0),
        (extent_ptrs_no_ptrs, 136, 0),
        (extent_ptrs_too_many_ptrs, 137, 0),
        (extent_ptrs_redundant_crc, 138, 0),
        (extent_ptrs_redundant_stripe, 139, 0),
        (extent_ptrs_unwritten, 140, 0),
        (extent_ptrs_written_and_unwritten, 141, 0),
        (extent_ptrs_all_invalid, 338, FSCK_AUTOFIX),
        (extent_ptrs_all_invalid_but_cached, 351, FSCK_AUTOFIX),
        (extent_reconcile_bad_pending, 332, 0),
        (extent_reconcile_bad_hipri, 333, 0),
        (extent_reconcile_bad_replicas, 339, 0),
        (ptr_to_invalid_device, 142, 0),
        (ptr_to_removed_device, 322, FSCK_AUTOFIX),
        (ptr_to_duplicate_device, 143, 0),
        (ptr_after_last_bucket, 144, 0),
        (ptr_before_first_bucket, 145, 0),
        (ptr_spans_multiple_buckets, 146, 0),
        (ptr_to_missing_backpointer, 147, FSCK_AUTOFIX),
        (ptr_to_missing_alloc_key, 148, FSCK_AUTOFIX),
        (ptr_to_missing_replicas_entry, 149, FSCK_AUTOFIX),
        (ptr_to_missing_stripe, 150, 0),
        (ptr_to_incorrect_stripe, 151, 0),
        (ptr_gen_newer_than_bucket_gen, 152, FSCK_AUTOFIX),
        (ptr_too_stale, 153, 0),
        (stale_dirty_ptr, 154, FSCK_AUTOFIX),
        (stale_ptr_with_no_stale_ptrs_feature, 327, FSCK_AUTOFIX),
        (ptr_bucket_data_type_mismatch, 155, 0),
        (ptr_cached_and_erasure_coded, 156, 0),
        (ptr_crc_uncompressed_size_too_small, 157, 0),
        (ptr_crc_uncompressed_size_too_big, 161, 0),
        (ptr_crc_uncompressed_size_mismatch, 300, 0),
        (ptr_crc_csum_type_unknown, 158, 0),
        (ptr_crc_compression_type_unknown, 159, 0),
        (ptr_crc_redundant, 160, 0),
        (ptr_crc_nonce_mismatch, 162, 0),
        (ptr_stripe_redundant, 163, 0),
        (extent_flags_not_at_start, 306, 0),
        (reservation_key_nr_replicas_invalid, 164, 0),
        (reflink_v_refcount_wrong, 165, FSCK_AUTOFIX),
        (reflink_v_pos_bad, 292, 0),
        (reflink_p_to_missing_reflink_v, 166, FSCK_AUTOFIX),
        (reflink_refcount_underflow, 293, 0),
        (stripe_pos_bad, 167, 0),
        (stripe_val_size_bad, 168, 0),
        (stripe_csum_granularity_bad, 290, 0),
        (stripe_sectors_zero, 340, 0),
        (stripe_sector_count_wrong, 169, FSCK_AUTOFIX),
        (stripe_parity_block_sector_count_wrong, 360, FSCK_AUTOFIX),
        (stripe_to_missing_bucket_ref, 346, FSCK_AUTOFIX),
        (bucket_stripe_ref_to_missing_stripe, 347, FSCK_AUTOFIX),
        (bucket_stripe_ref_to_incorrect_stripe, 348, FSCK_AUTOFIX),
        (stripe_update_stale_stripe_ptr, 354, FSCK_AUTOFIX),
        (snapshot_tree_pos_bad, 170, 0),
        (snapshot_tree_to_missing_snapshot, 171, 0),
        (snapshot_tree_to_missing_subvol, 172, 0),
        (snapshot_tree_to_wrong_subvol, 173, 0),
        (snapshot_tree_to_snapshot_subvol, 174, 0),
        (snapshot_pos_bad, 175, 0),
        (snapshot_parent_bad, 176, 0),
        (snapshot_children_not_normalized, 177, 0),
        (snapshot_child_duplicate, 178, 0),
        (snapshot_child_bad, 179, 0),
        (snapshot_skiplist_not_normalized, 180, 0),
        (snapshot_skiplist_bad, 181, 0),
        (snapshot_pad_nonzero, 370, 0),
        (snapshot_edge_bad, 371, 0),
        (snapshot_state_bad, 373, FSCK_AUTOFIX),
        (snapshot_state_bitflip, 379, FSCK_AUTOFIX),
        (snapshot_state_stale_tombstone, 382, FSCK_AUTOFIX),
        (snapshot_subvol_state_mismatch, 386, FSCK_AUTOFIX),
        (snapshot_deleted_but_subvol_live, 376, FSCK_AUTOFIX),
        (snapshot_deleted_has_live_children, 381, FSCK_AUTOFIX),
        (snapshot_deleted_but_linked, 384, FSCK_AUTOFIX),
        (snapshot_deleted_but_has_data, 385, FSCK_AUTOFIX),
        (snapshot_subvol_backref_wrong, 377, FSCK_AUTOFIX),
        (snapshot_no_keys_childless, 378, FSCK_AUTOFIX),
        (snapshot_should_not_have_subvol, 182, 0),
        (snapshot_subvol_flag_wrong, 369, FSCK_AUTOFIX),
        (snapshot_to_bad_snapshot_tree, 183, FSCK_AUTOFIX),
        (snapshot_bad_depth, 184, FSCK_AUTOFIX),
        (snapshot_bad_skiplist, 185, FSCK_AUTOFIX),
        (subvol_pos_bad, 186, 0),
        (subvol_pad_nonzero, 372, 0),
        (subvol_state_bad, 374, FSCK_AUTOFIX),
        (subvol_state_bitflip, 380, FSCK_AUTOFIX),
        (subvol_snapshot_not_leaf, 375, 0),
        (subvol_not_master_and_not_snapshot, 187, FSCK_AUTOFIX),
        (subvol_to_missing_root, 188, FSCK_AUTOFIX),
        (subvol_root_wrong_bi_subvol, 189, FSCK_AUTOFIX),
        (subvol_root_unlinked_flag_missing, 383, FSCK_AUTOFIX),
        (bkey_in_missing_snapshot, 190, 0),
        (bkey_in_deleted_snapshot, 315, FSCK_AUTOFIX),
        (inode_pos_inode_nonzero, 191, 0),
        (inode_pos_blockdev_range, 192, 0),
        (inode_alloc_cursor_inode_bad, 301, 0),
        (inode_unpack_error, 193, 0),
        (inode_str_hash_invalid, 194, 0),
        (inode_v3_fields_start_bad, 195, 0),
        (inode_snapshot_mismatch, 196, FSCK_AUTOFIX),
        (snapshot_key_missing_inode_snapshot, 314, FSCK_AUTOFIX),
        (inode_unlinked_but_clean, 197, 0),
        (inode_unlinked_but_nlink_nonzero, 198, 0),
        (inode_unlinked_and_not_open, 281, 0),
        (inode_unlinked_but_has_dirent, 285, FSCK_AUTOFIX),
        (unlinked_inode_not_on_deleted_list, 244, FSCK_AUTOFIX),
        (inode_checksum_type_invalid, 199, 0),
        (inode_compression_type_invalid, 200, 0),
        (inode_subvol_root_but_not_dir, 201, 0),
        (inode_i_size_dirty_but_clean, 202, FSCK_AUTOFIX),
        (inode_i_sectors_dirty_but_clean, 203, FSCK_AUTOFIX),
        (inode_i_sectors_wrong, 204, FSCK_AUTOFIX),
        (inode_dir_wrong_nlink, 205, FSCK_AUTOFIX),
        (inode_dir_multiple_links, 206, FSCK_AUTOFIX),
        (inode_dir_missing_backpointer, 284, FSCK_AUTOFIX),
        (inode_dir_unlinked_but_not_empty, 286, FSCK_AUTOFIX),
        (inode_dir_has_nonzero_i_size, 319, FSCK_AUTOFIX),
        (inode_multiple_links_but_nlink_0, 207, FSCK_AUTOFIX),
        (inode_wrong_backpointer, 208, FSCK_AUTOFIX),
        (inode_wrong_nlink, 209, FSCK_AUTOFIX),
        (inode_has_child_snapshots_wrong, 287, FSCK_AUTOFIX),
        (inode_unreachable, 210, FSCK_AUTOFIX),
        (inode_unreachable_dirent_in_descendant, 427, FSCK_AUTOFIX),
        (inode_journal_seq_in_future, 299, FSCK_AUTOFIX),
        (inode_i_sectors_underflow, 312, FSCK_AUTOFIX),
        (inode_has_case_insensitive_not_set, 316, FSCK_AUTOFIX),
        (inode_parent_has_case_insensitive_not_set, 317, FSCK_AUTOFIX),
        (vfs_inode_i_blocks_underflow, 311, FSCK_AUTOFIX),
        (vfs_inode_i_blocks_not_zero_at_truncate, 313, FSCK_AUTOFIX),
        (vfs_bad_inode_rm, 320, 0),
        (deleted_inode_but_clean, 211, FSCK_AUTOFIX),
        (deleted_inode_missing, 212, FSCK_AUTOFIX),
        (deleted_inode_is_dir, 213, FSCK_AUTOFIX),
        (deleted_inode_not_unlinked, 214, FSCK_AUTOFIX),
        (deleted_inode_has_child_snapshots, 288, FSCK_AUTOFIX),
        (extent_overlapping, 215, FSCK_AUTOFIX),
        (key_in_missing_inode, 216, FSCK_AUTOFIX),
        (key_in_wrong_inode_type, 217, 0),
        (extent_past_end_of_inode, 218, FSCK_AUTOFIX),
        (dirent_empty_name, 219, 0),
        (dirent_val_too_big, 220, 0),
        (dirent_name_too_long, 221, 0),
        (dirent_name_embedded_nul, 222, 0),
        (dirent_name_dot_or_dotdot, 223, 0),
        (dirent_name_has_slash, 224, 0),
        (dirent_d_type_wrong, 225, FSCK_AUTOFIX),
        (inode_bi_parent_wrong, 226, FSCK_AUTOFIX),
        (dirent_in_missing_dir_inode, 227, 0),
        (dirent_in_non_dir_inode, 228, 0),
        (dirent_to_missing_inode, 229, FSCK_AUTOFIX),
        (dirent_to_overwritten_inode, 302, FSCK_AUTOFIX),
        (dirent_to_missing_subvol, 230, FSCK_AUTOFIX),
        (dirent_to_itself, 231, 0),
        (dirent_casefold_mismatch, 318, FSCK_AUTOFIX),
        (quota_type_invalid, 232, 0),
        (xattr_val_size_too_small, 233, 0),
        (xattr_val_size_too_big, 234, 0),
        (xattr_invalid_type, 235, 0),
        (xattr_name_invalid_chars, 236, 0),
        (xattr_in_missing_inode, 237, 0),
        (root_subvol_missing, 238, FSCK_AUTOFIX),
        (root_dir_missing, 239, FSCK_AUTOFIX),
        (root_inode_not_dir, 240, FSCK_AUTOFIX),
        (dir_loop, 241, FSCK_AUTOFIX),
        (hash_table_key_duplicate, 242, FSCK_AUTOFIX),
        (hash_table_key_wrong_offset, 243, FSCK_AUTOFIX),
        (reflink_p_front_pad_bad, 245, 0),
        (journal_entry_dup_same_device, 246, 0),
        (inode_bi_subvol_missing, 247, FSCK_AUTOFIX),
        (inode_bi_subvol_wrong, 248, FSCK_AUTOFIX),
        (inode_points_to_missing_dirent, 249, FSCK_AUTOFIX),
        (inode_points_to_wrong_dirent, 250, FSCK_AUTOFIX),
        (inode_bi_parent_nonzero, 251, 0),
        (missing_inode_with_contents, 321, FSCK_AUTOFIX),
        (dirent_to_missing_parent_subvol, 252, 0),
        (dirent_not_visible_in_parent_subvol, 253, FSCK_AUTOFIX),
        (subvol_fs_path_parent_wrong, 254, FSCK_AUTOFIX),
        (subvol_root_fs_path_parent_nonzero, 255, 0),
        (subvol_children_not_set, 256, FSCK_AUTOFIX),
        (subvol_children_bad, 257, 0),
        (subvol_loop, 258, FSCK_AUTOFIX),
        (subvol_unreachable, 259, FSCK_AUTOFIX),
        (btree_node_bkey_bad_u64s, 260, 0),
        (btree_node_topology_empty_interior_node, 261, 0),
        (btree_ptr_v2_min_key_bad, 262, 0),
        (btree_root_unreadable_and_scan_found_nothing, 263, 0),
        (snapshot_node_missing, 264, FSCK_AUTOFIX),
        (dup_backpointer_to_bad_csum_extent, 265, FSCK_AUTOFIX),
        (btree_bitmap_not_marked, 266, FSCK_AUTOFIX),
        (sb_clean_entry_overrun, 267, 0),
        (btree_ptr_v2_written_0, 268, 0),
        (subvol_snapshot_bad, 269, 0),
        (subvol_inode_bad, 270, 0),
        (subvol_missing, 308, FSCK_AUTOFIX),
        (alloc_key_stripe_sectors_wrong, 271, FSCK_AUTOFIX),
        (accounting_mismatch, 272, FSCK_AUTOFIX),
        (accounting_replicas_not_marked, 273, FSCK_AUTOFIX),
        (accounting_to_invalid_device, 289, 0),
        (invalid_btree_id, 274, FSCK_AUTOFIX),
        (alloc_key_io_time_bad, 275, 0),
        (alloc_key_fragmentation_lru_wrong, 276, FSCK_AUTOFIX),
        (accounting_key_junk_at_end, 277, FSCK_AUTOFIX),
        (accounting_key_replicas_nr_devs_0, 278, FSCK_AUTOFIX),
        (accounting_key_replicas_nr_required_bad, 279, FSCK_AUTOFIX),
        (accounting_key_replicas_devs_unsorted, 280, FSCK_AUTOFIX),
        (accounting_key_version_0, 282, FSCK_AUTOFIX),
        (accounting_key_nr_counters_wrong, 307, FSCK_AUTOFIX),
        (accounting_key_underflow, 325, FSCK_AUTOFIX),
        (accounting_key_version_out_of_order, 326, FSCK_AUTOFIX),
        (logged_op_but_clean, 283, FSCK_AUTOFIX),
        (compression_opt_not_marked_in_sb, 295, FSCK_AUTOFIX),
        (compression_type_not_marked_in_sb, 296, FSCK_AUTOFIX),
        (compression_error, 342, 0),
        (data_update_got_non_extent, 350, 0),
        (directory_size_mismatch, 303, FSCK_AUTOFIX),
        (dirent_cf_name_too_big, 304, 0),
        (dirent_stray_data_after_cf_name, 305, 0),
        (reconcile_work_incorrectly_set, 309, FSCK_AUTOFIX),
        (reconcile_work_phys_incorrectly_set, 341, FSCK_AUTOFIX),
        (validate_error_in_commit, 329, 0),
        (extent_io_opts_not_set, 330, FSCK_AUTOFIX),
        (stripe_needs_reconcile_not_set, 352, FSCK_AUTOFIX),
        (stripe_can_widen_wrong, 361, FSCK_AUTOFIX),
        (extent_io_opts_unneeded, 331, FSCK_AUTOFIX),
        (reconcile_bp_to_missing_btree_ptr, 310, FSCK_AUTOFIX),
        (reconcile_bp_to_leaf_node_key, 334, FSCK_AUTOFIX),
        (btree_ptr_with_no_reconcile_bp, 335, FSCK_AUTOFIX),
        (btree_ptr_with_bad_reconcile_bp, 336, FSCK_AUTOFIX),
        (btree_ptr_to_bad_reconcile_bp, 337, FSCK_AUTOFIX),
        (vfs_i_size_bad, 343, 0),
        (vfs_i_sectors_bad, 344, 0),
        (vfs_unlink_got_wrong_inum, 349, 0),
        (device_bad_flush_forced_rewind, 357, 0),
        (journal_bucket_seq_not_monotonic, 358, 0),
        (dup_extents_to_reflink, 362, FSCK_AUTOFIX),
        (stripe_read_ptr_stale, 363, 0),
        (bkey_in_deleted_interior_snapshot, 364, FSCK_AUTOFIX),
        (inode_has_inode_opts_flag_wrong, 365, FSCK_AUTOFIX),
        (inode_has_access_acl_flag_wrong, 366, FSCK_AUTOFIX),
        (inode_has_default_acl_flag_wrong, 367, FSCK_AUTOFIX),
        (dirent_to_inode_in_descendant_snapshot, 368, FSCK_AUTOFIX),
        (damage_entries_bad, 387, 0),
        (damage_key_no_inode, 388, FSCK_AUTOFIX),
        (data_read_io_err_recovered, 389, 0),
        (data_read_io_err, 390, 0),
        (data_read_csum_err_recovered, 391, 0),
        (data_read_csum_err, 392, 0),
        (data_lost_device_removed, 393, 0),
        (blk_sts_notsupp, 394, 0),
        (blk_sts_timeout, 395, 0),
        (blk_sts_nospc, 396, 0),
        (blk_sts_transport, 397, 0),
        (blk_sts_target, 398, 0),
        (blk_sts_resv_conflict, 399, 0),
        (blk_sts_medium, 400, 0),
        (blk_sts_protection, 401, 0),
        (blk_sts_resource, 402, 0),
        (blk_sts_ioerr, 403, 0),
        (blk_sts_again, 404, 0),
        (blk_sts_dev_resource, 405, 0),
        (blk_sts_offline, 406, 0),
        (blk_sts_duration_limit, 407, 0),
        (blk_sts_inval, 408, 0),
        (blk_sts_removed, 409, 0),
        (blk_sts_unknown, 410, 0),
        (data_decompress_err_exceeded_max_encoded_extent, 411, 0),
        (data_decompress_err_lz4_old, 412, 0),
        (data_decompress_err_lz4, 413, 0),
        (data_decompress_err_gzip, 414, 0),
        (data_decompress_err_gzip_size_mismatch, 415, 0),
        (data_decompress_err_zstd_src_len_bad, 416, 0),
        (data_decompress_err_zstd_size_mismatch, 417, 0),
        (data_decompress_err_zstd_corruption_detected, 418, 0),
        (data_decompress_err_zstd_checksum_wrong, 419, 0),
        (data_decompress_err_zstd_prefix_unknown, 420, 0),
        (data_decompress_err_zstd_src_size_wrong, 421, 0),
        (data_decompress_err_zstd_dst_size_too_small, 422, 0),
        (data_decompress_err_zstd_memory_allocation, 423, 0),
        (data_decompress_err_zstd_unknown, 424, 0),
        (data_decompress_err_unknown, 425, 0),
        (snapshot_child_missing_but_accounted, 426, FSCK_AUTOFIX),
        (inode_opts_not_propagated, 428, FSCK_AUTOFIX),
        (stripe_read_csum_err, 429, 0),
        (stripe_reconstruct_failed, 430, 0),
        (data_lost_btree_node_read_error, 431, 0),
        (data_lost_double_allocation, 432, 0),
        (write_degraded_insufficient_devices, 433, 0),
        (write_degraded_no_progress, 434, 0),
        (backpointer_reconcile_phys_wrong, 435, FSCK_AUTOFIX),
        (device_bad_flush_repaired_from_replica, 436, 0),
        (MAX, 437, 0),
    }
}

macro_rules! __bch_sb_error_id_0 {
    ([$($acc:tt)*] $(($t:tt, $n:expr$(, $($__rest:tt)*)?)),* $(,)?) => { ::paste::paste! {
        c_enum! {
            #[open]
            pub enum bch_sb_error_id: u32 {
                $($acc)*
                $([<BCH_FSCK_ERR_ $t>] = (($n) as u32),)*
            }
        }
    } };
}
BCH_SB_ERRS!(__bch_sb_error_id_0 []);

#[repr(C, align(8))]
#[derive(Clone, Copy, Default, CStruct, TypeInfo)]
#[c_typedef(bch_sb_field_error_entry)]
pub struct bch_sb_field_error_entry {
    pub v: le::U64,
    pub last_error_time: le::U64,
}

#[repr(C)]
#[derive(Clone, Copy, Default, CStruct, TypeInfo)]
pub struct bch_sb_field_errors {
    pub field: c::bch_sb_field,
    pub entries: [c::bch_sb_field_error_entry; 0],
}

c_bitmask! {
    LE64_BITMASK(struct bch_sb_field_error_entry, v) {
        BCH_SB_ERROR_ENTRY_ID(0, 16),
        BCH_SB_ERROR_ENTRY_NR(16, 64),
    }
}

/*
 * v2 entries add the time of first occurrence: id (16 bits), a
 * saturating occurrence count (32), and two 40-bit second-resolution
 * timestamps - good until the year ~36,800 - packed exactly into 128
 * bits. No 64-bit boundary partition fits {16, 32, 40, 40}, so
 * last_error_time spans the two words: in Rust the entry is one
 * little-endian u128, where the fields are contiguous; C has the two
 * words and hand-rolled accessors, whose setters saturate, since a
 * wrapped count or timestamp would be worse than a pinned one.
 *
 * v[0]: id 0..16, nr 16..48, last_error_time 48..64 (low 16 bits)
 * v[1]: last_error_time 0..24 (high 24 bits), first_error_time 24..64
 */
#[bitfield(u128, repr = le::U128, from = le::U128::new, into = le::U128::get)]
pub struct bch_sb_field_error_entry_v2_bits {
    #[bits(16)]
    pub id: u16,
    #[bits(32)]
    pub nr: u32,
    #[bits(40)]
    pub last_error_time: u64,
    #[bits(40)]
    pub first_error_time: u64,
}

#[repr(C, align(8))]
#[derive(Clone, Copy, Default, CStruct, TypeInfo)]
#[c_typedef(bch_sb_field_error_entry_v2)]
pub struct bch_sb_field_error_entry_v2 {
    #[c("__le64 v[2]")]
    pub v: bch_sb_field_error_entry_v2_bits,
}

#[repr(C)]
#[derive(Clone, Copy, Default, CStruct, TypeInfo)]
pub struct bch_sb_field_errors_v2 {
    pub field: c::bch_sb_field,
    pub entries: [c::bch_sb_field_error_entry_v2; 0],
}

c_const! {
    pub const BCH_SB_ERROR_ENTRY_V2_NR_MAX: u64 = (1 << 32) - 1;
}

c_const! {
    pub const BCH_SB_ERROR_ENTRY_V2_TIME_MAX: u64 = (1 << 40) - 1;
}
