#ifndef RLIBBCACHEFS_H
#define RLIBBCACHEFS_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


#endif /* RLIBBCACHEFS_H */
