// Auto-generated from BCH_BTREE_IDS() - do not edit

pub const BTREE_IDS_KNOWN: &[c::btree_id] = &[
    c::btree_id::extents,
    c::btree_id::inodes,
    c::btree_id::dirents,
    c::btree_id::xattrs,
    c::btree_id::alloc,
    c::btree_id::quotas,
    c::btree_id::stripes,
    c::btree_id::reflink,
    c::btree_id::subvolumes,
    c::btree_id::snapshots,
    c::btree_id::lru,
    c::btree_id::freespace,
    c::btree_id::need_discard,
    c::btree_id::backpointers,
    c::btree_id::bucket_gens,
    c::btree_id::snapshot_trees,
    c::btree_id::deleted_inodes,
    c::btree_id::logged_ops,
    c::btree_id::reconcile_work,
    c::btree_id::subvolume_children,
    c::btree_id::accounting,
    c::btree_id::reconcile_hipri,
    c::btree_id::reconcile_pending,
    c::btree_id::reconcile_scan,
    c::btree_id::reconcile_work_phys,
    c::btree_id::reconcile_hipri_phys,
    c::btree_id::bucket_to_stripe,
    c::btree_id::stripe_backpointers,
];
