name: Commit Check

on:
  push:
  pull_request:
    branches: "master"

jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: commit-check/commit-check-action@v1
        with:
          message: false
          branch: false
          author-name: false
          author-email: false
          commit-signoff: true
          dry-run: false
          job-summary: true
